export const state = {
  itemsUnread: {
    items: [
      {
        id:
          "https://www.inputmag.com/tech/in-south-korea-your-samsung-phone-can-function-as-a-car-key",
        url:
          "https://www.inputmag.com/tech/in-south-korea-your-samsung-phone-can-function-as-a-car-key",
        external_url:
          "https://www.inputmag.com/tech/in-south-korea-your-samsung-phone-can-function-as-a-car-key",
        title: "In South Korea, your Samsung phone can function as a car key",
        content_html:
          '<img src="https://imgix.bustle.com/uploads/getty/2021/9/30/e6acb17c-0920-41e2-a9ab-8a13987eca93-getty-1343771155.jpg?w=500&amp;fit=max&amp;auto=format%2Ccompress" /><br /><p>Samsung <a href="https://www.samsungmobilepress.com/pressreleases/unlock-a-new-experience-galaxy-users-can-now-use-secure-digital-car-key-with-genesis-gv60" target="_blank" rel="noreferrer">has begun rolling out support</a> for digital car keys starting in South Korea with the all-electric Genesis GV60. The feature, which works with several recent Samsung smartphones, allows users to lock their car and start it even if they don’t have the physical keys on them. </p><p>Supported devices include the Samsung Galaxy S21 Plus and Ultra, Note 20 Ultra, and Galaxy Z Fold 2 and 3. So if you live in South Korea, you have one of those phones, <em>and</em> you bought the new GV60, you’ll be able to take advantage of “passive entry.” That means you can unlock and lock your car without pulling out your phone. So long as it’s nearby, you’ll also be able to start your car. </p><p><u>Security —</u> That’s pretty convenient, and Samsung says it’s secure too. The digital keys are stored in an “embedded Secure Element (eSE),” basically a dedicated chip housed inside the phone that stores information in an encrypted manner. Users can share a car key with someone else running Android 11 that has a supported phone. </p><p>Samsung’s digital car keys use ultra-wideband technology, a wireless protocol that transmits high-frequency radio waves. The company says this enables highly accurate spatial awareness so the car and phone can communicate without any delays or other issues. </p><img src="https://imgix.bustle.com/uploads/image/2021/9/30/2c35127e-0dae-4548-b9f0-f3e29cf8f881-001_genesis_samsung_digital_key.webp?w=500&amp;fit=max&amp;auto=format%2Ccompress" /><p><u>Paltry support —</u> Obviously, few people are actually going to be able to take advantage of this. But Samsung has partnerships with Audi, BMW, and Ford, so hopefully we’ll see more cars supported soon. Anyone who’s ever had a car key go missing knows that digital keys could be a big lifesaver. </p><p>Apple actually <a href="https://www.inputmag.com/tech/apple-will-let-you-unlock-your-car-with-your-iphone">added support for digital car keys</a> in iOS 14, but there too just a select few cars actually support it at this point. It’s really going to be more widely supported in newer vehicles that integrate NFC technology. </p>',
        author: "Tom Maxwell",
        created_at: 1633092385000,
        date_modified: 1633092385000,
        date_published: 1633092385000,
        feed_title: "Input",
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        categories: ["Samsung", "Automotive", "Smartphones", "Tech", "Apps"],
        feed_color: [0, 65, 50],
        _id: "649ad653-f1dbc84d",
        styles: {
          fontClasses: { heading: "headerFontSans2", body: "bodyFontSerif3" },
          border: false,
          hasColorBlockquoteBG: true,
          dropCapFamily: "body",
          dropCapIsMonochrome: false,
          dropCapSize: 3,
          dropCapIsDrop: false,
          dropCapIsBold: true,
          dropCapIsStroke: false,
          color: [257, 20, 50],
          isMainColorDarker: false,
          isCoverImageColorDarker: false,
          isCoverInline: false,
          showCoverImage: false,
          coverImage: {
            showCoverImage: false,
            isBW: false,
            isMultiply: true,
            isScreen: false,
            isCoverImageColorDarker: false,
            color: "orange2",
            resizeMode: "cover",
            align: "center",
            isInline: false,
          },
          title: {
            isMonochrome: true,
            color: [257, 20, 50],
            interBolded: [
              false,
              true,
              true,
              false,
              true,
              true,
              false,
              true,
              false,
              false,
              true,
              true,
            ],
            textAlign: "left",
            title:
              "In South Korea, your Samsung phone can function as a car key",
            isVertical: false,
            isInline: false,
            isUpperCase: true,
            lineHeightAsMultiplier: 0.9750224955161386,
            invertBG: false,
            invertedBGMargin: 1,
            isItalic: false,
            bg: false,
            hasShadow: false,
            valign: "top",
            isBold: false,
            excerptInvertBG: false,
            excerptFullWidth: true,
            excerptHorizontalAlign: "right",
            fontSize: 62,
            lineHeight: 62,
            fontResized: true,
          },
        },
        original_created_at: 1633092385000,
        date_fetched: 1633093214054,
      },
      {
        id:
          "https://www.inputmag.com/gaming/bluepoint-games-to-join-sony-as-internal-developer",
        url:
          "https://www.inputmag.com/gaming/bluepoint-games-to-join-sony-as-internal-developer",
        external_url:
          "https://www.inputmag.com/gaming/bluepoint-games-to-join-sony-as-internal-developer",
        title: "Bluepoint games to join Sony as an internal developer",
        content_html:
          '<img src="https://imgix.bustle.com/uploads/image/2021/9/30/6987791c-6281-4f10-8982-cc049b38bb72-demonsouls1.png?w=500&amp;fit=max&amp;auto=format%2Ccompress" /><br /><p>Bluepoint Games is a developer that doesn’t exactly fit the traditional mold. Founded in 2006, the Austin-based video game company creates remakes of older titles and brings them into the fold of the contemporary console landscape. On Thursday, Sony <a href="https://blog.playstation.com/2021/09/30/welcoming-bluepoint-games-to-the-playstation-studios-family/" target="_blank" rel="noreferrer">announced</a> that it has acquired Bluepoint after a long-running partnership. The developer will join Playstation Studios and its next project will apparently be an original game. In some ways, the move feels reminiscent of a filmmaker that has helped create other movies and now gets to realize their own vision.   </p><p>If you don’t know the developer by name, Bluepoint remade <em>Demon’s Souls</em>, which was originally released for the Playstation 3 in 2009, for the Playstation 5. It has also helmed the remake of <em>Shadow of the Colossus </em>and<em> Uncharted: The Nathan Drake Collection </em>for Playstation 4. </p><p>In a <a href="https://www.youtube.com/watch?v=3OH977tutoE" target="_blank" rel="noreferrer">video</a> that welcomes Bluepoint into the Playstation Family, Marco Thrush, president of the company, shared the direction for the acquisition: “We believe this will empower Bluepoint to create even more impactful games for Playstation gamers.” As the gaming industry becomes bigger and bigger, some of the dominant forces are recognizing that smaller studios and <a href="https://www.inputmag.com/gaming/netflix-has-bought-its-first-game-development-studio-night-school-studio">indie developers</a> will be key to remaining on the cutting edge of the business. </p><div class="bHd"><div class="TBI"></div><noscript><iframe src="https://www.youtube.com/embed/tnNJo_-v1EU" data-videoid="tnNJo_-v1EU" class="TBI"></iframe></noscript></div><p><u>A deep catalog —</u> Aside from the aforementioned titles, Bluepoint began its relationship with Playstation through the development of the <em><em>God of War Collection</em> </em>for the Playstation 3 in 2009. Following this, the company moved onto the <em><em>Metal Gear Solid HD Collection</em> </em>for both Playstation 3 and Xbox 360 in 2011. It will be interesting to see what an original looks like from Bluepoint. Exactly how long has this been a goal for the company? Will the game take any cues from the iconic franchises the developer has already worked on? What genre will it slot into? Hopefully these questions are answered sooner rather than later. </p><p>To take a big picture outlook, I wonder how the spree of recent acquisitions by high-profile gaming companies will affect the indie scene. While it is possible to exist outside the orbit of a Microsoft or Sony, will these smaller companies change the way they create in order to net a partnership? Hopefully the scene does not get over-saturated with studios that are trying to create games with universal appeal in mind. I want to see the <em>Undertale</em>s of the world continue to thrive and <a href="https://www.inputmag.com/gaming/thanks-to-deltarune-surprise-game-releases-are-having-a-moment">break the conventions</a> of the industry. </p>',
        author: "Will Gendron",
        created_at: 1633089385000,
        date_modified: 1633089385000,
        date_published: 1633089385000,
        feed_title: "Input",
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        categories: ["Microsoft", "Gaming", "Sony", "PlayStation 5"],
        feed_color: [0, 65, 50],
        _id: "8599add3-f1dbc84d",
        styles: {
          fontClasses: { heading: "headerFontSans1", body: "bodyFontSerif3" },
          border: false,
          hasColorBlockquoteBG: false,
          dropCapFamily: "header",
          dropCapIsMonochrome: false,
          dropCapSize: 6,
          dropCapIsDrop: false,
          dropCapIsBold: false,
          dropCapIsStroke: false,
          color: [257, 20, 50],
          isMainColorDarker: true,
          isCoverImageColorDarker: false,
          isCoverInline: false,
          showCoverImage: false,
          coverImage: {
            showCoverImage: false,
            isBW: false,
            isMultiply: false,
            isScreen: false,
            isCoverImageColorDarker: false,
            color: "yellow2",
            resizeMode: "cover",
            align: "center",
            isInline: false,
          },
          title: {
            isMonochrome: true,
            color: [257, 20, 50],
            interBolded: false,
            textAlign: "left",
            title: "Bluepoint games to join Sony as an internal developer",
            isVertical: false,
            isInline: false,
            isUpperCase: false,
            lineHeightAsMultiplier: 1.096369122540455,
            invertBG: false,
            invertedBGMargin: 1,
            isItalic: true,
            bg: true,
            hasShadow: false,
            valign: "middle",
            isBold: true,
            excerptFullWidth: false,
            excerptHorizontalAlign: "right",
            fontSize: 64,
            lineHeight: 64,
            fontResized: true,
          },
        },
        original_created_at: 1633089385000,
        date_fetched: 1633093214054,
      },
      {
        id:
          "https://www.inputmag.com/gaming/ikea-made-appearance-at-the-tokyo-game-show",
        url:
          "https://www.inputmag.com/gaming/ikea-made-appearance-at-the-tokyo-game-show",
        external_url:
          "https://www.inputmag.com/gaming/ikea-made-appearance-at-the-tokyo-game-show",
        title: "Ikea made an appearance at the Tokyo Game Show",
        content_html:
          '<img src="https://imgix.bustle.com/uploads/image/2021/9/30/9ac7a925-1a6e-42e7-8221-a43dd8335c98-377c2f688b13cc7a5201c46bb2db2dea.jpeg?w=500&amp;fit=max&amp;auto=format%2Ccompress" /><br /><p>Ikea sees gaming as an untapped market for its simple yet functional furniture, and earlier this year <a href="https://www.inputmag.com/design/ikea-rog-collab-gaming-furniture-is-all-grown-up">partnered</a> with ASUS’ Republic of Gamers brand to debut a series of products like standing desks and gaming chairs. Perhaps to emphasize its seriousness about entering this market, Ikea made a surprise appearance at the 2021 Tokyo Game Show, where it had a small booth contained within ASUS’ area, <em>Gizmodo</em> <a href="https://kotaku.com/ikea-is-serious-enough-to-attend-japans-biggest-gaming-1847772902" target="_blank" rel="noreferrer">reported</a>. The booth served as a place to show off the full line of products, thirty items in total. </p><p>Unfortunately, due to the pandemic, this year’s Tokyo Game Show was mostly held online; the in-person show floor was only open to press and other industry insiders. But it’s still interesting to see that a furniture company synonymous with affordable basics was there. </p><div class="XeQ"><blockquote class="twitter-tweet" data-tweetid="1443435883764457474"><a href="https://twitter.com/gizmodojapan/status/1443435883764457474"></a></blockquote></div><p><u>Gaming furniture —</u> Ikea isn’t exactly known for making things that are super high quality. In fact, it’s really thought of as a purveyor of disposable furniture that you’ll eventually grow out of and into more long-lasting tables and other goods as you get older and settle down. But the gaming products that it has unveiled actually look fairly good, and some will like that they are less garish than other gaming furniture tends to be, with accents like bright neon colors and RGB lights. The Ikea line is subdued in comparison. </p><p>Ikea has been doing more collaborations in general, such as with the release of its <a href="https://www.inputmag.com/design/ikea-and-sonos-update-symfonisk-table-lamp-speaker-with-customizable-shades">table lamp</a> that features an integrated Sonos speaker. These types of partnerships help the furniture company to create affordable products that still pack a punch, as it can combine other companies’ expertise with its own skill at driving down costs to make something that’s not great but good enough. </p>',
        author: "Tom Maxwell",
        created_at: 1633050846000,
        date_modified: 1633050846000,
        date_published: 1633050846000,
        feed_title: "Input",
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        categories: [
          "Design",
          "Gaming",
          "Home",
          "IKEA",
          "video games",
          "Business",
        ],
        feed_color: [0, 65, 50],
        _id: "38a18965-f1dbc84d",
        styles: {
          fontClasses: { heading: "headerFontSans1", body: "bodyFontSerif3" },
          border: false,
          hasColorBlockquoteBG: true,
          dropCapFamily: "body",
          dropCapIsMonochrome: false,
          dropCapSize: 5,
          dropCapIsDrop: true,
          dropCapIsBold: false,
          dropCapIsStroke: true,
          color: [257, 20, 50],
          isMainColorDarker: false,
          isCoverImageColorDarker: true,
          isCoverInline: false,
          showCoverImage: false,
          coverImage: {
            showCoverImage: false,
            isBW: false,
            isMultiply: false,
            isScreen: false,
            isCoverImageColorDarker: true,
            color: "yellow1",
            resizeMode: "cover",
            align: "center",
            isInline: false,
          },
          title: {
            isMonochrome: true,
            color: [257, 20, 50],
            interBolded: false,
            textAlign: "left",
            title: "Ikea made an appearance at the Tokyo Game Show",
            isVertical: false,
            isInline: true,
            isUpperCase: false,
            lineHeightAsMultiplier: 1.0191858644200844,
            invertBG: false,
            invertedBGMargin: 2,
            isItalic: false,
            bg: true,
            hasShadow: false,
            valign: "middle",
            isBold: false,
            excerptFullWidth: true,
            excerptHorizontalAlign: "right",
            fontSize: 64,
            lineHeight: 64,
            fontResized: true,
          },
        },
        original_created_at: 1633050846000,
        date_fetched: 1633093214054,
      },
      {
        id:
          "https://www.inputmag.com/culture/petty-amazon-whips-out-receipts-of-spacexs-legal-battles",
        url:
          "https://www.inputmag.com/culture/petty-amazon-whips-out-receipts-of-spacexs-legal-battles",
        external_url:
          "https://www.inputmag.com/culture/petty-amazon-whips-out-receipts-of-spacexs-legal-battles",
        title: "Petty Amazon whips out receipts of SpaceX’s legal battles",
        content_html:
          '<img src="https://imgix.bustle.com/uploads/getty/2021/9/30/b865f330-e651-491d-bfbd-e3216fca91ad-getty-1193818202.jpg?w=500&amp;fit=max&amp;auto=format%2Ccompress" /><br /><p>Elon Musk, for <a href="https://www.inputmag.com/culture/technoking-elon-musk-semi-separates-from-grimes">all his faults</a> (and <a href="https://www.inputmag.com/culture/elon-musk-hates-the-new-pro-union-electric-vehicle-bill">we do mean</a> <a href="https://www.inputmag.com/tech/elon-musk-disappointed-with-teslas-latest-self-driving-tech-beta"><em>all </em>of them</a>), beautifully summed up Jeff Bezos’s <a href="https://www.inputmag.com/culture/nasa-says-yeah-jeff-bezos-tantrum-is-definitely-delaying-its-moon-trip">ongoing temper tantrum</a> against NASA for <a href="https://www.inputmag.com/culture/jeff-bezos-is-suing-nasa-because-it-hurt-his-feelings">jilting Blue Origin’s lunar lander proposal</a>. “You can’t sue your way to the moon, no matter how good your lawyers are,” the Technoking quipped during a Code Conference event on Tuesday, and you know what? Fair. Perhaps unsurprisingly, Team Bezos did not find this amusing. </p><p>Still, it was somewhat absurd to learn that <a href="https://www.inputmag.com/tech/fcc-approves-amazons-plan-to-launch-thousands-of-kuiper-internet-satellites-to-rival-elon-musk-spacex-starlink">Project Kuiper</a> — Amazon’s satellite branch — then sent a <a href="https://www.theverge.com/2021/9/29/22700600/amazon-elon-musk-jeff-bezos-blue-origin-spacex-lawsuits" target="_blank" rel="noreferrer">completely unsolicited email to <em>The Verge</em></a> defending Dear Leader Jeff’s space company by providing <a href="https://go.redirectingat.com/?id=66960X1514734&amp;xs=1&amp;url=https://www.scribd.com/document/528420595/SpaceX-Litigation-Protests&amp;referrer=theverge.com&amp;sref=https://www.theverge.com/2021/9/29/22700600/amazon-elon-musk-jeff-bezos-blue-origin-spacex-lawsuits&amp;xcust=___vg__p_22464641__t_w__d_D" target="_blank" rel="noreferrer">a 13-page categorized list</a> of past SpaceX legal entanglements with the government that stretches back to 2004. Totally normal behavior you want to see from people responsible for sending human beings into the depths of space.</p><p><u>Yes. 13 pages long —</u> “Attached is a list of some of the times SpaceX has sued the U.S. government on procurement matters and protested various governmental decisions... It is difficult to reconcile their own historical record with their recent position on others filing similar actions,” a Project Kuiper spokesperson wrote in the message. “We agree fully,” someone from Blue Origin confirmed to <em>The Verge</em> when followed up for comment. Very cool and normal and good stuff here.</p><p><u> Didn’t take long for Musk to see it —</u> Not long after <em>The Verge</em> published Amazon’s meticulous Burn Book of SpaceX litigations, Elon Musk came to his company’s defense via — where else — Twitter. “SpaceX has sued to be *allowed* to compete,” <a href="https://twitter.com/elonmusk/status/1443302848096178178" target="_blank" rel="noreferrer">Musk tweeted</a>, adding that Blue Origin instead “is suing to stop competition.” Po-<em>tay</em>-to/Po-<em>tah</em>-to.</p><p>It’s a bit of a semantic argument there, and one that honestly doesn’t matter in the grand scheme of things. NASA wants to go with SpaceX and has every right to do so, especially when Blue Origin’s alternative <a href="https://www.gao.gov/assets/b-419783.pdf" target="_blank" rel="noreferrer">didn’t even take into account the darkness of space</a>.</p><p><u>The Bezos Multiverse —</u> Zooming out a bit here, it’s definitely disconcerting to see a completely separate business entity (Amazon/Project Kuiper) go to bat for another Bezos brand (Blue Origin), with these organizations working in tandem to promote its overseer’s goals. It gets even more troublesome when you consider just how powerful any one of these companies are, with Amazon obviously leading the pack. If only there was a term to describe this kind of situation where a single person or group consolidates all of its economic and political power to stifle any and all competition...</p>',
        author: "Andrew Paul",
        created_at: 1633049842000,
        date_modified: 1633049842000,
        date_published: 1633049842000,
        feed_title: "Input",
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        categories: [
          "Amazon",
          "Culture",
          "Elon Musk",
          "Politics",
          "SpaceX",
          "Lawsuit",
          "Jeff Bezos",
          "internet",
          "Business",
          "Blue Origin",
        ],
        feed_color: [0, 65, 50],
        _id: "70f75aeb-f1dbc84d",
        styles: {
          fontClasses: { heading: "headerFontSans2", body: "bodyFontSerif1" },
          border: false,
          hasColorBlockquoteBG: true,
          dropCapFamily: "header",
          dropCapIsMonochrome: false,
          dropCapSize: 4,
          dropCapIsDrop: false,
          dropCapIsBold: false,
          dropCapIsStroke: true,
          color: [257, 20, 50],
          isMainColorDarker: false,
          isCoverImageColorDarker: true,
          isCoverInline: false,
          showCoverImage: false,
          coverImage: {
            showCoverImage: false,
            isBW: false,
            isMultiply: false,
            isScreen: false,
            isCoverImageColorDarker: true,
            color: "orange2",
            resizeMode: "cover",
            align: "left",
            isInline: false,
          },
          title: {
            isMonochrome: true,
            color: [257, 20, 50],
            interBolded: false,
            textAlign: "left",
            title: "Petty Amazon whips out receipts of SpaceX’s legal battles",
            isVertical: false,
            isInline: true,
            isUpperCase: true,
            lineHeightAsMultiplier: 0.990823025522328,
            invertBG: false,
            invertedBGMargin: 1,
            isItalic: false,
            bg: false,
            hasShadow: true,
            valign: "top",
            isBold: false,
            excerptInvertBG: true,
            excerptFullWidth: true,
            excerptHorizontalAlign: "center",
            fontSize: 62,
            lineHeight: 62,
            fontResized: true,
          },
        },
        original_created_at: 1633049842000,
        date_fetched: 1633093214054,
      },
      {
        id:
          "https://www.inputmag.com/gaming/a-twisted-metal-reboot-is-reportedly-in-the-works",
        url:
          "https://www.inputmag.com/gaming/a-twisted-metal-reboot-is-reportedly-in-the-works",
        external_url:
          "https://www.inputmag.com/gaming/a-twisted-metal-reboot-is-reportedly-in-the-works",
        title: "A 'Twisted Metal' reboot is reportedly in the works",
        content_html:
          '<img src="https://imgix.bustle.com/uploads/image/2021/9/30/6e44d0fd-0620-4200-a605-65006fbb4f39-twistedmetal1.jpeg?w=500&amp;fit=max&amp;auto=format%2Ccompress" /><br /><p>The keys to Twisted Metal, one of the most recognizable franchises of the original Playstation, will be <a href="https://www.videogameschronicle.com/news/sources-destruction-all-stars-studio-lucid-handed-twisted-metal-revival/" target="_blank" rel="noreferrer">handed over to </a><em>Destruction AllStars </em>developer<em> </em>Lucid Games for an upcoming reboot, according to <em>Video Games Chronicle</em>. Originally released in 1995, the vehicular combat game established itself as one of the most successful franchises for the first Playstation. By 2000, the series had already gotten up to four games and sales were close to the 5 million mark. By the time the new game actually comes to market, it will have been a decade since the franchise last put out a fresh installment. </p><p>Lucid Games is a Liverpool-based studio that previously helmed the development of <em>Destruction AllStars</em>, another combat-racing game that was released in February to <a href="https://www.ign.com/articles/destruction-allstars-review" target="_blank" rel="noreferrer">tepid reviews</a>. Hopefully some of the bumps and bruises from that process will lead to a smoother launch for <em>Twisted Metal</em>. Either way, the revival is supposed to coincide with the release of a <a href="https://variety.com/2021/tv/news/twisted-metal-tv-series-deadpool-writers-1234911825/" target="_blank" rel="noreferrer">TV series</a> based on the video game, according to <em>VGC</em>. Writers from the Deadpool films and <em>Zombieland</em> are being tapped for that endeavor. </p><p>The next iteration of Twisted<em> </em>Metal will reportedly also be free-to-play, which is an interesting move considering the game has a storied history. There will almost certainly be some cosmetic items for purchase and given the absurdity of some of the gear that’s been part of the series, I expect to seem some Cronenberg-esque options. </p><img src="https://imgix.bustle.com/uploads/image/2021/9/30/da7c484c-d018-4c02-8cd5-ad0bde3945c7-twistedmetal2.jpeg?w=500&amp;fit=max&amp;auto=format%2Ccompress" /><p><u>Moving on? —</u> Since the <a href="https://twitter.com/_Tom_Henderson_/status/1426288447258599427" target="_blank" rel="noreferrer">rumors</a> of a new entry to the Twisted Metal franchise started circulating, David Jaffe, the original director, has spoken out about his displeasure at not being included in the talks. The game, after all, took off under his watch. Jaffe uploaded a <a href="https://www.youtube.com/watch?v=5m23Bkcvz_c" target="_blank" rel="noreferrer">video</a> to his personal YouTube channel after the original <em>VGC</em> report. “Let’s be clear: Sony owes me nothing, our relationship ended somewhere in late 2018,” he stated. “But I will say that, emotionally, it feels shitty, if any of this is true, to not have been contacted at all.” Yeah, that puts a damper on things. </p><p>Still, I look forward to wreaking havoc as an HDR-enhanced Sweet Tooth. </p><img src="https://imgix.bustle.com/uploads/image/2021/9/30/85a45046-0c17-4f4d-8535-5e765e1f1fb6-twistedmetal3.jpeg?w=500&amp;fit=max&amp;auto=format%2Ccompress" />',
        author: "Will Gendron",
        created_at: 1633048562000,
        date_modified: 1633048562000,
        date_published: 1633048562000,
        feed_title: "Input",
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        categories: ["Gaming", "PlayStation", "Sony", "TV"],
        feed_color: [0, 65, 50],
        _id: "3eca5093-f1dbc84d",
        styles: {
          fontClasses: { heading: "headerFontSans3", body: "bodyFontSerif1" },
          border: true,
          hasColorBlockquoteBG: true,
          dropCapFamily: "body",
          dropCapIsMonochrome: false,
          dropCapSize: 3,
          dropCapIsDrop: true,
          dropCapIsBold: false,
          dropCapIsStroke: false,
          color: [257, 20, 50],
          isMainColorDarker: true,
          isCoverImageColorDarker: false,
          isCoverInline: false,
          showCoverImage: false,
          coverImage: {
            showCoverImage: false,
            isBW: true,
            isMultiply: true,
            isScreen: false,
            isCoverImageColorDarker: false,
            color: "green3",
            resizeMode: "cover",
            align: "center",
            isInline: false,
          },
          title: {
            isMonochrome: true,
            color: [257, 20, 50],
            interBolded: [
              false,
              true,
              true,
              true,
              false,
              true,
              false,
              false,
              true,
            ],
            textAlign: "left",
            title: "A 'Twisted Metal' reboot is reportedly in the works",
            isVertical: false,
            isInline: false,
            isUpperCase: true,
            lineHeightAsMultiplier: 0.9480435193633416,
            invertBG: false,
            invertedBGMargin: 1,
            isItalic: false,
            bg: false,
            hasShadow: false,
            valign: "top",
            isBold: false,
            excerptInvertBG: true,
            excerptFullWidth: true,
            excerptHorizontalAlign: "right",
            fontSize: 64,
            lineHeight: 64,
            fontResized: true,
          },
        },
        original_created_at: 1633048562000,
        date_fetched: 1633093214054,
      },
      {
        id:
          "https://www.inputmag.com/culture/ex-onlyfans-employees-got-ahold-of-sensitive-user-data-after-leaving",
        url:
          "https://www.inputmag.com/culture/ex-onlyfans-employees-got-ahold-of-sensitive-user-data-after-leaving",
        external_url:
          "https://www.inputmag.com/culture/ex-onlyfans-employees-got-ahold-of-sensitive-user-data-after-leaving",
        title:
          "Ex-OnlyFans employees got ahold of sensitive user data after leaving",
        content_html:
          '<img src="https://imgix.bustle.com/uploads/getty/2021/9/30/d938b909-8a29-40c4-8e68-ed0b75604287-getty-1327230167.jpg?w=500&amp;fit=max&amp;auto=format%2Ccompress" /><br /><p>Multiple former employees of OnlyFans could access both models’ and patrons’ personal account information long after they left the company. Although ex-staff were no longer able to use the site’s backend information, they reportedly still could access Zendesk, a popular third-party customer support ticket service, which provided a loophole for amassing “credit card information, drivers\' licenses, passports, full names, addresses, bank statements, how much they have earned on OnlyFans or spent, Know Your Customer (KYC) selfies where the creator holds up an ID next to their face for verification, and model release forms.”</p><p>The news comes courtesy of a <a href="https://www.vice.com/en/article/4avjvq/former-onlyfans-employees-user-personal-data-security-risk" target="_blank" rel="noreferrer">new report out earlier today from<em> Motherboard</em></a>, which spoke with multiple credible, anonymous sources on the subject. These kinds of security lapses are dangerous and abusive in any circumstance, but they pose particular risks to sex workers such as OnlyFans models, who often face threats of violence, cyberstalking, revenge porn, and blackmailing.</p><p><u>Continuing controversy for the company —</u> The security issue is only the latest in a string of bad news for OnlyFans, whose owners faced severe backlash for their <a href="https://www.inputmag.com/culture/onlyfans-confirms-the-porn-ban-in-email-to-creators-updated-terms-of-service">brief attempt to ban pornography</a> from the site — subject matter on which OnlyFans built its empire. While <a href="https://www.inputmag.com/tech/onlyfans-founder-says-porn-ban-was-caused-by-a-crackdown-from-banks">citing changes in bank policies</a> as the reason for the controversial decision, the anger and public criticisms soon <a href="https://www.inputmag.com/culture/onlyfans-backtracks-on-no-porn-policy-following-backlash">forced the company to reverse course</a>.</p><p><u>Far more positive hacking news —</u> Thankfully, it’s not all gross abuses of power and privilege when it comes to incidents involving vast quantities of users’ personal data. Just earlier this month, Epik — the web service company responsible for hosting such online hellscapes as Gab, The Donald, and Parler — had virtually <a href="https://www.inputmag.com/culture/epik-web-host-to-nazis-maga-cultists-got-itself-hacked">its entire site’s history and information stolen</a>, providing activists, researchers, and journalists massive quantities of (potentially <em>very</em> embarrassing) information to parse through. How’s that for a palate cleanser?</p>',
        author: "Andrew Paul",
        created_at: 1633042188000,
        date_modified: 1633042188000,
        date_published: 1633042188000,
        feed_title: "Input",
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        categories: [
          "Culture",
          "Cybersecurity",
          "Hacks",
          "Security",
          "Privacy",
          "internet",
          "OnlyFans",
        ],
        feed_color: [0, 65, 50],
        _id: "5a3d3acb-f1dbc84d",
        styles: {
          fontClasses: { heading: "headerFontSans2", body: "bodyFontSerif1" },
          border: false,
          hasColorBlockquoteBG: true,
          dropCapFamily: "body",
          dropCapIsMonochrome: false,
          dropCapSize: 4,
          dropCapIsDrop: true,
          dropCapIsBold: true,
          dropCapIsStroke: true,
          color: [257, 20, 50],
          isMainColorDarker: true,
          isCoverImageColorDarker: false,
          isCoverInline: false,
          showCoverImage: false,
          coverImage: {
            showCoverImage: false,
            isBW: false,
            isMultiply: false,
            isScreen: false,
            isCoverImageColorDarker: false,
            color: "blue1",
            resizeMode: "cover",
            align: "center",
            isInline: false,
          },
          title: {
            isMonochrome: true,
            color: [257, 20, 50],
            interBolded: false,
            textAlign: "left",
            title:
              "Ex-OnlyFans employees got ahold of sensitive user data after leaving",
            isVertical: false,
            isInline: true,
            isUpperCase: false,
            lineHeightAsMultiplier: 1.0648066933557416,
            invertBG: false,
            invertedBGMargin: 2,
            isItalic: false,
            bg: true,
            hasShadow: false,
            valign: "middle",
            isBold: true,
            excerptFullWidth: false,
            excerptHorizontalAlign: "center",
            fontSize: 58,
            lineHeight: 58,
            fontResized: true,
          },
        },
        original_created_at: 1633042188000,
        date_fetched: 1633093214054,
      },
      {
        id:
          "https://www.inputmag.com/tech/lil-nas-x-is-getting-official-tiktok-nft",
        url:
          "https://www.inputmag.com/tech/lil-nas-x-is-getting-official-tiktok-nft",
        external_url:
          "https://www.inputmag.com/tech/lil-nas-x-is-getting-official-tiktok-nft",
        title: "A Lil Nas X video will be turned into a TikTok official NFT",
        content_html:
          '<img src="https://imgix.bustle.com/uploads/getty/2021/9/30/f07d4987-79f0-4f8c-9b0f-99ca13a187a1-getty-1340822953.jpg?w=500&amp;fit=max&amp;auto=format%2Ccompress" /><br /><p>Lil Nas X, ever one to release a stunt project, is going to get an official TikTok NFT, according to <em><a href="https://variety.com/2021/digital/news/lil-nas-x-official-tiktok-nfts-1235077960/" target="_blank" rel="noreferrer">Variety</a></em>. The NFT will be based on the “Montero (Call Me By Your Name)” video. It’s unclear if the artist plans to sell said NFT, but if he does, history suggests he probably stands to make a pretty penny. </p><p>Grimes and other celebrities are also getting NFTs from TikTok. But on top of some recent <a href="https://www.nbcnews.com/nbc-out/out-pop-culture/dolly-parton-responds-lil-nas-xs-cover-jolene-best-way-rcna2461" target="_blank" rel="noreferrer">flattering comments</a> about him made by Dolly Parton, Lil Nas X is having a good week.</p><p><u>Pyramid scheme —</u> Even though <a href="https://www.inputmag.com/culture/linkin-park-mike-shinoda-happy-endings-nft-interview">NFTs</a> are just digital objects of inscrutable value, a huge market for them has boomed. Just one marketplace for buying and selling NFTs, OpenSea, last month reported it surpassed $1 billion in sales in a single week. But an <a href="https://www.cnbc.com/2021/09/15/opensea-insider-trading-rumors-are-true.html" target="_blank" rel="noreferrer">insider trading scandal at that company</a> highlights a reality of NFTs, which is that there’s a lot of scamming going on. People hope by jacking up the price of an NFT, other people will see the potential to make some money and themselves purchase the NFT off the last buyer, and so on and so forth. </p><p>Either way, maybe someone will see value in buying the “exclusive” right to say they own the Lil Nas X NFT. Anyone can view it, but only one person will have the certificate of authenticity. That could have some inherent value to someone, but more likely a person would buy the NFT in hopes that they can flip it on the open market for a profit. </p><p><u>Hype cycle —</u> There’s hope in some corners that the hype cycle surrounding NFTs will die down, celebrities will stop auctioning off meaningless artwork, and we’ll be left in a place where small creators are able to make something of a living by selling creations to their biggest fans. You could imagine supporting your favorite creators and collecting items like you might have baseball cards in the past. But we’re still in a period where everyone is seeing the mega sales of NFTs and hoping they can get in on the action. A lot of inexplicable sales, like the <a href="https://www.inputmag.com/culture/people-are-buying-free-clipart-rock-nfts-for-millions-of-dollars">$1.3 million purchase of a rock picture</a>, are really just people hoping that they can create artificial demand and sell their NFT to the next sucker. </p>',
        author: "Tom Maxwell",
        created_at: 1633039910000,
        date_modified: 1633039910000,
        date_published: 1633039910000,
        feed_title: "Input",
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        categories: [
          "Cryptocurrency",
          "Tech",
          "social media",
          "Business",
          "NFT",
        ],
        feed_color: [0, 65, 50],
        _id: "c887929e-f1dbc84d",
        styles: {
          fontClasses: { heading: "headerFontSerif1", body: "bodyFontSans1" },
          border: true,
          hasColorBlockquoteBG: true,
          dropCapFamily: "header",
          dropCapIsMonochrome: true,
          dropCapSize: 4,
          dropCapIsDrop: false,
          dropCapIsBold: true,
          dropCapIsStroke: false,
          color: [257, 20, 50],
          isMainColorDarker: false,
          isCoverImageColorDarker: true,
          isCoverInline: false,
          showCoverImage: false,
          coverImage: {
            showCoverImage: false,
            isBW: false,
            isMultiply: false,
            isScreen: true,
            isCoverImageColorDarker: true,
            color: "yellow2",
            resizeMode: "cover",
            align: "center",
            isInline: false,
          },
          title: {
            isMonochrome: true,
            color: [257, 20, 50],
            interBolded: [
              false,
              true,
              true,
              true,
              true,
              false,
              false,
              true,
              false,
              false,
              true,
              true,
              true,
            ],
            textAlign: "left",
            title:
              "A Lil Nas X video will be turned into a TikTok official NFT",
            isVertical: false,
            isInline: false,
            isUpperCase: false,
            lineHeightAsMultiplier: 1.0551291614228993,
            invertBG: false,
            invertedBGMargin: 1,
            isItalic: false,
            bg: false,
            hasShadow: true,
            valign: "top",
            isBold: false,
            excerptInvertBG: true,
            excerptFullWidth: true,
            excerptHorizontalAlign: "left",
          },
        },
        original_created_at: 1633039910000,
        date_fetched: 1633093214054,
      },
      {
        id:
          "https://www.inputmag.com/design/this-bike-claims-to-be-the-lightest-around-at-just-19-pounds",
        url:
          "https://www.inputmag.com/design/this-bike-claims-to-be-the-lightest-around-at-just-19-pounds",
        external_url:
          "https://www.inputmag.com/design/this-bike-claims-to-be-the-lightest-around-at-just-19-pounds",
        title: "This e-bike claims to be the lightest around at just 19 pounds",
        content_html:
          '<img src="https://imgix.bustle.com/uploads/image/2021/9/30/4aaa89bd-de25-4cf2-b86f-217603c54254-ares-bike-1.jpeg?w=500&amp;fit=max&amp;auto=format%2Ccompress" /><br /><p>Italian firm Ares Design has <a href="https://www.aresdesign.com/en-us/news-press/ares_super_leggera_by_hps_/" target="_blank" rel="noreferrer">unveiled</a> what it claims is the world’s lightest electric bicycle. The Super Leggera weighs just under 20 lbs, and features a 200-watt motor that provides cyclists a small boost as they pedal. </p><p>The bike was designed in partnership with High Performance Systems (HPS), an engineering company that specializes in mobility technology. Just 24 of the bikes are being manufactured initially, at a steep price of €18,950 (approximately $22,000). </p><p>While the road bike looks decidedly aesthetically pleasing, its low-powered motor raises some questions. Other e-bikes feature motors closer to the 500-watt range, which provide a noticeable boost as you pedal uphill. Still, 200 watts is definitely better than nothing. </p><p><u>E-bike considerations —</u> And while it’s interesting that the Super Legerra is lightweight, with an e-bike, weight isn’t as important because again, you’re being assisted as you pedal. It’s like you have another person pedaling in tandem with you, requiring only a fraction of the energy you might otherwise need to exert. With e-bikes, it kind of makes more sense to use <a href="https://www.inputmag.com/guides/the-best-electric-bikes-for-the-coming-apocalypse">heavier but inexpensive components</a>, including a larger, heavier battery and motor. Ares hasn’t disclosed the size of the Super Legerra’s battery, but it’s likely small. </p><img src="https://imgix.bustle.com/uploads/image/2021/9/30/8cfb7035-1f4e-4d8c-9891-ad9da05e3886-aresebikecrank.jpeg?w=500&amp;fit=max&amp;auto=format%2Ccompress" /><p>Professional cyclists shun e-bikes, and with good reason, until there are e-bike races training on one is only effective if you turn off all assistance and contend with the added weight. Casual riders, meanwhile, will likely prefer something cheaper with a bigger motor. But there’s a market for everything, and we’re sure 24 people with loads of disposable cash will be happy to part with it for a bike this good-looking... or who don’t want observers to realize they’re riding an e-bike — in which case, the <a href="https://www.inputmag.com/tech/bike-maker-scott-unveils-sleekly-integrated-patron-e-bike">Scott Patron eRide</a> is another option.</p>',
        author: "Tom Maxwell",
        created_at: 1633036431000,
        date_modified: 1633036431000,
        date_published: 1633036431000,
        feed_title: "Input",
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        categories: [
          "Design",
          "Transportation",
          "Electric Vehicle",
          "electric bike",
          "hardware",
          "e-bike",
        ],
        feed_color: [0, 65, 50],
        _id: "730e1cfc-f1dbc84d",
        styles: {
          fontClasses: { heading: "headerFontSans1", body: "bodyFontSerif3" },
          border: false,
          hasColorBlockquoteBG: true,
          dropCapFamily: "body",
          dropCapIsMonochrome: false,
          dropCapSize: 4,
          dropCapIsDrop: false,
          dropCapIsBold: false,
          dropCapIsStroke: true,
          color: [257, 20, 50],
          isMainColorDarker: true,
          isCoverImageColorDarker: false,
          isCoverInline: false,
          showCoverImage: false,
          coverImage: {
            showCoverImage: false,
            isBW: false,
            isMultiply: false,
            isScreen: false,
            isCoverImageColorDarker: false,
            color: "blue2",
            resizeMode: "cover",
            align: "center",
            isInline: false,
          },
          title: {
            isMonochrome: true,
            color: [257, 20, 50],
            interBolded: [
              false,
              true,
              true,
              false,
              false,
              false,
              true,
              true,
              false,
              true,
              true,
              true,
            ],
            textAlign: "left",
            title:
              "This e-bike claims to be the lightest around at just 19 pounds",
            isVertical: false,
            isInline: true,
            isUpperCase: false,
            lineHeightAsMultiplier: 1.0021273318447106,
            invertBG: false,
            invertedBGMargin: 0,
            isItalic: false,
            bg: true,
            hasShadow: false,
            valign: "middle",
            isBold: true,
            excerptFullWidth: false,
            excerptHorizontalAlign: "right",
          },
        },
        original_created_at: 1633036431000,
        date_fetched: 1633093214054,
      },
      {
        id:
          "https://www.inputmag.com/culture/facebook-reiterates-to-the-senate-its-inability-to-keep-kids-safe",
        url:
          "https://www.inputmag.com/culture/facebook-reiterates-to-the-senate-its-inability-to-keep-kids-safe",
        external_url:
          "https://www.inputmag.com/culture/facebook-reiterates-to-the-senate-its-inability-to-keep-kids-safe",
        title:
          "Facebook reiterates to the Senate its inability to keep kids safe",
        content_html:
          '<img src="https://imgix.bustle.com/uploads/getty/2021/9/30/c8739fa6-324f-43b0-acb9-59308a6c0340-getty-1235413074.jpg?w=500&amp;fit=max&amp;auto=format%2Ccompress" /><br /><p>Today, members of the Senate’s consumer protection subcommittee took turns questioning Facebook’s head of global safety, Antigone Davis, on how Facebook and Instagram are <a href="https://www.inputmag.com/culture/facebook-publishes-heavily-annotated-research-instagrams-toxicity">protecting their youngest users from harm</a>. The subcommittee hearing was called in response to<a href="https://www.wsj.com/articles/facebook-knows-instagram-is-toxic-for-teen-girls-company-documents-show-11631620739" target="_blank" rel="noreferrer"> <em>The Wall Street Journal</em>’s damning report</a> about Facebook’s “toxic” effects on teenagers.</p><p>The hearing, which lasted <a href="https://twitter.com/mattdwille/status/1443591283050647553?s=20" target="_blank" rel="noreferrer">nearly two and a half hours</a>, ended up being somewhat repetitive, perhaps because there are only so many interesting questions one can ask about this particular topic. The vast majority of the questioning attempted to clarify why Facebook had been sitting on all this research showing the harm it causes some of its users without really doing much at all about it.</p><p>“Facebook routinely puts profits ahead of kids’ online safety, chooses the growth of its products over the wellbeing of our children, and it’s delinquent to take action,” said Sen. Richard Blumenthal (D-Conn.) by way of introduction. “It’s failing to hold itself accountable.”</p><p>In her own introductory statements, Davis explained that her team works “tirelessly” to make sure kids have a positive experience. Her responses throughout the hearing attempted to bolster this assertion, but, by and large, they only served to underscore that Facebook’s problems are of its own making.</p><p><u>A systemic problem —</u> Facebook’s pushback to the <em>WSJ</em> report has mostly revolved around what it deemed a “simply inaccurate” analysis of leaked research. Most of today’s hearing amounted to a back-and-forth about why, exactly Facebook hadn’t done <em>anything</em> about this information, which clearly points to Instagram and Facebook being harmful. (Though, if prompted, Facebook will still argue with you about the implications of that data.)</p><p>One refrain underscored Davis’ entire testimony: Facebook is doing everything it can. She spoke to, amongst other solutions, the fact that targeted advertising is limited for teenagers; she pointed to forthcoming pilot features for “nudging” users toward uplifting posts and for encouraging users to “take a break” from its platforms.</p><p><u>Dangerous by design —</u> The problem with this framing is that adding features and restricting access to others can never really mitigate the mental health effects of being on Facebook and Instagram in the first place. The harms we’re discussing are caused by the platforms’ most basic functions. </p><img src="https://imgix.bustle.com/uploads/getty/2021/9/30/2b60f11c-5ecb-4fe6-be1f-fefbbddeed04-getty-1235603741.jpg?w=500&amp;fit=max&amp;auto=format%2Ccompress" /><p>Liking photos, suggestion algorithms, influencers looking surreally beautiful, depressing news — those are the bedrock upon which Facebook and Instagram are built. With each of its platforms, Facebook’s goal is to keep users scrolling so they can see the ads from which it makes money. Algorithms are fine-tuned to serve up whatever drives engagement, and that’s often harmful, shocking, or enraging content. To really “fix” the problem would, from Facebook’s side of things, mean totally reassessing how its platforms work and what they choose to prioritize.</p><p><u>So how do we fix it? —</u> The Senate subcommittee’s purpose for today’s hearing was muddled at best. Some questions — like Sen. Dan Sullivan’s (R-Alaska) meandering ones about the Chinese Communist Party — had only passing significance to the pre-determined task of “protecting kids online.”</p><p>Because Facebook’s toxicity is very much rooted in its base functions, there’s no way for the company to mitigate these harms on its own. This really is why the Senate has stepped in here. The hope is that rooting through these issues with lawmakers will accelerate the policymaking process. Laws that govern how internet companies deal with and protect children are outdated. The Children’s Internet Protection Act (CIPA) was enacted in 2000. That’s an eternity in internet time. Facebook and Instagram didn’t even exist at the turn of the millennium.</p><p><u>Facebook needs to play ball —</u> Sen. Blumenthal made the subcommittee’s hopes clear in his introductory statements: that Facebook would not only cooperate with updated policies but also help in pushing for those regulations to pass. If Facebook is genuine in its assertions that it wants to protect children and foster a positive environment, it ought to accept regulation with open arms. It won’t, though. It will only change the status quo when not doing so will cost it money, and enough money to matter. Paltry fines of a few million dollars won’t do it — Facebook makes billions each year. </p><p>In today’s hearing, Davis was asked specifically whether or not Facebook would commit to supporting updated bills like the Kids Internet Design and Safety (KIDS) Act. Her response? The standard deflection comeback: “I’d be happy to follow up.” Which is Facebook speak for, “Not unless we’re forced to.” It’s time to ditch the conciliatory carrot and crack the legislative whip instead.</p><p>The next part of the subcommittee’s hearing will question a whistleblower who reportedly leaked “thousands” of research documents to the Senate. The hearing will be held <a href="https://www.commerce.senate.gov/2021/10/protecting%20kids%20online:%20testimony%20from%20a%20facebook%20whistleblower" target="_blank" rel="noreferrer">on Tuesday, October 5, at 10 a.m. ET</a>.</p>',
        author: "Matt Wille",
        created_at: 1633034557000,
        date_modified: 1633034557000,
        date_published: 1633034557000,
        feed_title: "Input",
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        categories: [
          "Facebook",
          "Culture",
          "Instagram",
          "Policy",
          "Politics",
          "Tech",
          "Privacy",
          "social media",
          "Teens",
          "Teenagers",
        ],
        feed_color: [0, 65, 50],
        _id: "1b7afc56-f1dbc84d",
        styles: {
          fontClasses: { heading: "headerFontSans1", body: "bodyFontSerif2" },
          border: true,
          hasColorBlockquoteBG: false,
          dropCapFamily: "body",
          dropCapIsMonochrome: false,
          dropCapSize: 2,
          dropCapIsDrop: false,
          dropCapIsBold: false,
          dropCapIsStroke: false,
          color: [257, 20, 50],
          isMainColorDarker: false,
          isCoverImageColorDarker: true,
          isCoverInline: false,
          showCoverImage: false,
          coverImage: {
            showCoverImage: false,
            isBW: false,
            isMultiply: false,
            isScreen: false,
            isCoverImageColorDarker: true,
            color: "orange1",
            resizeMode: "cover",
            align: "right",
            isInline: false,
          },
          title: {
            isMonochrome: true,
            color: [257, 20, 50],
            interBolded: [
              true,
              true,
              false,
              false,
              true,
              false,
              true,
              false,
              true,
              true,
              true,
            ],
            textAlign: "center",
            title:
              "Facebook reiterates to the Senate its inability to keep kids safe",
            isVertical: false,
            isInline: false,
            isUpperCase: true,
            lineHeightAsMultiplier: 0.9002436102525738,
            invertBG: false,
            invertedBGMargin: 2,
            isItalic: false,
            bg: false,
            hasShadow: true,
            valign: "bottom",
            isBold: false,
            excerptInvertBG: true,
            excerptFullWidth: false,
            excerptHorizontalAlign: "left",
          },
        },
        original_created_at: 1633034557000,
        date_fetched: 1633093214054,
      },
      {
        _id: "89505846-f1dbc84d",
        content_length: 3257,
        created_at: 1633032863000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/tech/jeep-unveils-its-first-plug-in-hybrid-variant-of-the-grand-cherokee",
        title:
          "Jeep unveils its first plug-in hybrid variant of the Grand Cherokee",
        url:
          "https://www.inputmag.com/tech/jeep-unveils-its-first-plug-in-hybrid-variant-of-the-grand-cherokee",
      },
      {
        _id: "c2db439e-f1dbc84d",
        content_length: 4108,
        created_at: 1633029385000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/design/fairphone-4-is-a-sustainable-smartphone-that-doesnt-skimp-on-features",
        title:
          "Fairphone 4 is a ‘sustainable smartphone’ that doesn’t skimp on features",
        url:
          "https://www.inputmag.com/design/fairphone-4-is-a-sustainable-smartphone-that-doesnt-skimp-on-features",
      },
      {
        _id: "8709fe1e-f1dbc84d",
        content_length: 2804,
        created_at: 1633028632000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/design/the-extreme-s1-x-is-an-e-scooter-that-goes-62-miles-hour",
        title: "The Extreme S1-X electric scooter can do 62 miles an hour",
        url:
          "https://www.inputmag.com/design/the-extreme-s1-x-is-an-e-scooter-that-goes-62-miles-hour",
      },
      {
        _id: "b1252b01-f1dbc84d",
        content_length: 2873,
        created_at: 1633026353000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/tech/white-house-may-invoke-a-cold-war-era-law-to-look-into-chip-shortages",
        title:
          "White House may invoke a Cold War-era law to look into chip shortages",
        url:
          "https://www.inputmag.com/tech/white-house-may-invoke-a-cold-war-era-law-to-look-into-chip-shortages",
      },
      {
        _id: "089a9a75-f1dbc84d",
        content_length: 14661,
        created_at: 1633022933000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/guides/heres-everything-i-needed-during-and-after-hurricane-ida",
        title: "Here’s everything I needed during (and after) Hurricane Ida",
        url:
          "https://www.inputmag.com/guides/heres-everything-i-needed-during-and-after-hurricane-ida",
      },
      {
        _id: "88b58a04-f1dbc84d",
        content_length: 4969,
        created_at: 1633015657000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/culture/a-travis-scott-mcdonalds-action-figure-is-reselling-for-55000",
        title:
          "A Travis Scott McDonald’s action figure is reselling for $55,000",
        url:
          "https://www.inputmag.com/culture/a-travis-scott-mcdonalds-action-figure-is-reselling-for-55000",
      },
      {
        _id: "f1d79db7-f1dbc84d",
        content_length: 4762,
        created_at: 1633014581000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/culture/facebook-publishes-heavily-annotated-research-instagrams-toxicity",
        title:
          "Facebook publishes heavily annotated research on Instagram's toxicity",
        url:
          "https://www.inputmag.com/culture/facebook-publishes-heavily-annotated-research-instagrams-toxicity",
      },
      {
        _id: "54626643-f1dbc84d",
        content_length: 2143,
        created_at: 1633014175000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/style/adidas-channels-the-kawasaki-ninja-for-a-rousing-zx-8000-sneaker",
        title:
          "Adidas channels the Kawasaki Ninja for a rousing ZX 8000 sneaker",
        url:
          "https://www.inputmag.com/style/adidas-channels-the-kawasaki-ninja-for-a-rousing-zx-8000-sneaker",
      },
      {
        _id: "73c627e0-f1dbc84d",
        content_length: 18281,
        created_at: 1633006825000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/reviews/sonos-beam-gen-2-review-what-is-this-incredible-soundbar-wizardry",
        title:
          "Sonos Beam (Gen 2) review: What is this incredible soundbar wizardry?",
        url:
          "https://www.inputmag.com/reviews/sonos-beam-gen-2-review-what-is-this-incredible-soundbar-wizardry",
      },
      {
        _id: "65c64630-f1dbc84d",
        content_length: 6122,
        created_at: 1633006825000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/tech/nreal-air-ar-glasses-look-less-dorky-works-with-iphone-price-release-date-features",
        title: "Nreal Air AR glasses look less dorky and will work with iPhone",
        url:
          "https://www.inputmag.com/tech/nreal-air-ar-glasses-look-less-dorky-works-with-iphone-price-release-date-features",
      },
      {
        _id: "418ca02d-f1dbc84d",
        content_length: 3793,
        created_at: 1632956505000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/tech/plantlife-aims-to-be-the-tiktok-of-plants",
        title: "PlantLife aims to be the TikTok of... plants",
        url:
          "https://www.inputmag.com/tech/plantlife-aims-to-be-the-tiktok-of-plants",
      },
      {
        _id: "d522e6ca-f1dbc84d",
        content_length: 425,
        created_at: 1632952825000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/reviews/instagrams-most-powerful-flashlight-blinded-me-with-scammy-promo-vids",
        title: "'World's most powerful flashlight' is a huge scam",
        url:
          "https://www.inputmag.com/reviews/instagrams-most-powerful-flashlight-blinded-me-with-scammy-promo-vids",
      },
      {
        _id: "8ef77ba9-f1dbc84d",
        content_length: 3057,
        created_at: 1632951805000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/culture/cops-sue-tesla-after-a-drunk-driver-hit-them-while-using-autopilot",
        title:
          "Cops sue Tesla after a drunk driver hit them while using autopilot",
        url:
          "https://www.inputmag.com/culture/cops-sue-tesla-after-a-drunk-driver-hit-them-while-using-autopilot",
      },
      {
        _id: "cfd5e458-f1dbc84d",
        content_length: 6529,
        created_at: 1632951085000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/tech/leaked-pricing-hints-pixel-6-pro-will-not-be-cheap",
        title: "Leaked pricing hints Pixel 6 Pro will not be cheap",
        url:
          "https://www.inputmag.com/tech/leaked-pricing-hints-pixel-6-pro-will-not-be-cheap",
      },
      {
        _id: "de87896e-f1dbc84d",
        content_length: 5111,
        created_at: 1632950226000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/gaming/all-the-corny-memes-in-the-halo-infinite-beta-detract-from-the-cool-stuff",
        title:
          "All the corny memes in the ‘Halo Infinite’ beta detract from the cool stuff",
        url:
          "https://www.inputmag.com/gaming/all-the-corny-memes-in-the-halo-infinite-beta-detract-from-the-cool-stuff",
      },
      {
        _id: "838b0bbf-f1dbc84d",
        content_length: 3010,
        created_at: 1632948265000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/style/adidas-money-printed-jeremy-scott-wings-sneaker-is-now-a-low-top",
        title:
          "Adidas’ money-printed Jeremy Scott ‘Wings’ sneaker is now a low top",
        url:
          "https://www.inputmag.com/style/adidas-money-printed-jeremy-scott-wings-sneaker-is-now-a-low-top",
      },
      {
        _id: "934fa438-f1dbc84d",
        content_length: 5750,
        created_at: 1632947605000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/reviews/weworks-all-access-plan-changed-my-life-during-the-pandemic",
        title: "WeWork's All Access plan saved my sanity during the pandemic",
        url:
          "https://www.inputmag.com/reviews/weworks-all-access-plan-changed-my-life-during-the-pandemic",
      },
      {
        _id: "63973f42-f1dbc84d",
        content_length: 3929,
        created_at: 1632947000000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/gaming/netflix-has-bought-its-first-game-development-studio-night-school-studio",
        title: "Netflix has bought its first game development studio",
        url:
          "https://www.inputmag.com/gaming/netflix-has-bought-its-first-game-development-studio-night-school-studio",
      },
      {
        _id: "ee0b92e9-f1dbc84d",
        content_length: 2742,
        created_at: 1632946409000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/tech/apple-claims-ipad-mini-jelly-scrolling-issue-is-on-purpose",
        title: "Apple claims iPad mini ‘jelly scrolling’ issue is on purpose",
        url:
          "https://www.inputmag.com/tech/apple-claims-ipad-mini-jelly-scrolling-issue-is-on-purpose",
      },
      {
        _id: "684192f1-f1dbc84d",
        content_length: 469,
        created_at: 1632944623000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/culture/steve-aoki-sothebys-nft-sales-interview",
        title: "Steve Aoki hypes 5 of his favorite NFT art pieces",
        url:
          "https://www.inputmag.com/culture/steve-aoki-sothebys-nft-sales-interview",
      },
      {
        _id: "c9d1486d-f1dbc84d",
        content_length: 440,
        created_at: 1632942134000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/guides/11-new-ios-15-features-you-need-to-try-right-now",
        title: "11 new iOS 15 features you need to try right now",
        url:
          "https://www.inputmag.com/guides/11-new-ios-15-features-you-need-to-try-right-now",
      },
      {
        _id: "ac786433-f1dbc84d",
        content_length: 3234,
        created_at: 1632941298000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/culture/amazon-is-trying-to-poach-macys-iconic-nyc-billboard-location",
        title: "Amazon is trying to poach Macy's iconic NYC billboard location",
        url:
          "https://www.inputmag.com/culture/amazon-is-trying-to-poach-macys-iconic-nyc-billboard-location",
      },
      {
        _id: "35615d09-f1dbc84d",
        content_length: 3704,
        created_at: 1632939455000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/tech/youtube-has-only-now-today-banned-anti-vaccine-misinformation",
        title:
          "YouTube has only now, today, banned anti-vaccine misinformation",
        url:
          "https://www.inputmag.com/tech/youtube-has-only-now-today-banned-anti-vaccine-misinformation",
      },
      {
        _id: "39eef331-f1dbc84d",
        content_length: 3055,
        created_at: 1632939298000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/style/kim-kardashians-balenciaga-met-gala-look-is-now-a-halloween-costume",
        title:
          "Kim Kardashian’s Balenciaga Met Gala look is now a Halloween costume",
        url:
          "https://www.inputmag.com/style/kim-kardashians-balenciaga-met-gala-look-is-now-a-halloween-costume",
      },
      {
        _id: "ad9453f9-f1dbc84d",
        content_length: 3620,
        created_at: 1632937362000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/tech/facebook-marketplace-filled-with-scammers-using-it-for-crime-report-says",
        title: "Facebook Marketplace is a hotbed of crime, report says",
        url:
          "https://www.inputmag.com/tech/facebook-marketplace-filled-with-scammers-using-it-for-crime-report-says",
      },
      {
        _id: "3f4f08f9-f1dbc84d",
        content_length: 3520,
        created_at: 1632936897000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/style/kanye-west-has-been-spotted-wearing-nike-for-the-third-time-this-year",
        title:
          "Kanye West has been spotted wearing Nike for the third time this year",
        url:
          "https://www.inputmag.com/style/kanye-west-has-been-spotted-wearing-nike-for-the-third-time-this-year",
      },
      {
        _id: "4eedac29-f1dbc84d",
        content_length: 2502,
        created_at: 1632936241000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/gaming/you-can-use-your-pc-as-a-super-powered-bluetooth-headset-for-nintendo-switch",
        title:
          "You can use your PC as a super-powered Bluetooth headset for Nintendo Switch",
        url:
          "https://www.inputmag.com/gaming/you-can-use-your-pc-as-a-super-powered-bluetooth-headset-for-nintendo-switch",
      },
      {
        _id: "031d575f-f1dbc84d",
        content_length: 4878,
        created_at: 1632935898000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/gaming/dear-game-publishers-whats-up-with-all-the-cringy-memes",
        title: "Dear game publishers: what's up with all the cringy memes?",
        url:
          "https://www.inputmag.com/gaming/dear-game-publishers-whats-up-with-all-the-cringy-memes",
      },
      {
        _id: "54b92ad9-f1dbc84d",
        content_length: 3771,
        created_at: 1632935217000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/culture/youtube-removed-the-i-cant-believe-youve-done-this-meme-video",
        title:
          "YouTube briefly removed the ‘I Can't Believe You've Done This’ meme video",
        url:
          "https://www.inputmag.com/culture/youtube-removed-the-i-cant-believe-youve-done-this-meme-video",
      },
      {
        _id: "f7afe892-f1dbc84d",
        content_length: 2786,
        created_at: 1632934194000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/tech/tesla-will-hold-monthly-10k-raffle-for-employees-who-are-vaccinated",
        title:
          "Tesla to hold $10K raffles for vaxxed workers so you'll forget it put them at risk",
        url:
          "https://www.inputmag.com/tech/tesla-will-hold-monthly-10k-raffle-for-employees-who-are-vaccinated",
      },
      {
        _id: "04016609-f1dbc84d",
        content_length: 3089,
        created_at: 1632931147000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/style/underwear-worn-by-michael-jordan-sold-for-3k-at-auction",
        title: "Underwear worn by Michael Jordan sold for over $3K at auction",
        url:
          "https://www.inputmag.com/style/underwear-worn-by-michael-jordan-sold-for-3k-at-auction",
      },
      {
        _id: "7b0662e2-f1dbc84d",
        content_length: 3464,
        created_at: 1632931053000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/tech/valve-is-working-on-a-standalone-vr-headset-to-rival-oculus-quest",
        title:
          "Valve is working on a standalone VR headset to rival Oculus Quest",
        url:
          "https://www.inputmag.com/tech/valve-is-working-on-a-standalone-vr-headset-to-rival-oculus-quest",
      },
      {
        _id: "ca13c92e-f1dbc84d",
        content_length: 4057,
        created_at: 1632927136000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/tech/amazons-astro-is-bad-at-basically-everything-developers-say",
        title: "Amazon's Astro is bad at basically everything, developers say",
        url:
          "https://www.inputmag.com/tech/amazons-astro-is-bad-at-basically-everything-developers-say",
      },
      {
        _id: "9d5c0c00-f1dbc84d",
        content_length: 2436,
        created_at: 1632923746000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/style/yeezy-gap-launches-its-first-hoodies-for-under-100",
        title: "Yeezy Gap launches its first hoodies — and they’re flying fast",
        url:
          "https://www.inputmag.com/style/yeezy-gap-launches-its-first-hoodies-for-under-100",
      },
      {
        _id: "d86974d6-f1dbc84d",
        content_length: 2083,
        created_at: 1632921840000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/tech/google-wants-you-to-cover-your-iphone-home-screen-with-its-apps",
        title:
          "Google wants to blanket your iPhone home screen with its services",
        url:
          "https://www.inputmag.com/tech/google-wants-you-to-cover-your-iphone-home-screen-with-its-apps",
      },
      {
        _id: "0e211314-f1dbc84d",
        content_length: 558,
        created_at: 1632898826000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/tech/withings-scanwatch-horizon-is-a-classy-dive-watch-with-health-sleep-heart-tracking",
        title:
          "Withings ScanWatch Horizon is a classy dive watch with health tracking",
        url:
          "https://www.inputmag.com/tech/withings-scanwatch-horizon-is-a-classy-dive-watch-with-health-sleep-heart-tracking",
      },
      {
        _id: "c0a7791a-f1dbc84d",
        content_length: 4027,
        created_at: 1632873685000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/gaming/google-stadia-on-tvs-now-supports-phones-as-gamepads",
        title:
          "Google Stadia on TVs now supports using your phone as a gamepad",
        url:
          "https://www.inputmag.com/gaming/google-stadia-on-tvs-now-supports-phones-as-gamepads",
      },
      {
        _id: "2632bd02-f1dbc84d",
        content_length: 4316,
        created_at: 1632872994000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/gaming/we-just-got-another-look-at-the-new-pokemon-games-coming-to-switch",
        title:
          "We just got another look at the new Pokémon games coming to Switch",
        url:
          "https://www.inputmag.com/gaming/we-just-got-another-look-at-the-new-pokemon-games-coming-to-switch",
      },
      {
        _id: "5e742a3f-f1dbc84d",
        content_length: 2824,
        created_at: 1632867159000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/gaming/super-nintendo-worlds-rumored-donkey-kong-area-is-coming-in-2024",
        title:
          "Super Nintendo World’s rumored Donkey Kong area is coming in 2024",
        url:
          "https://www.inputmag.com/gaming/super-nintendo-worlds-rumored-donkey-kong-area-is-coming-in-2024",
      },
      {
        _id: "f4ad1d06-f1dbc84d",
        content_length: 476,
        created_at: 1632865822000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/tech/heres-every-product-amazon-just-announced",
        title: "Here's every product Amazon just announced",
        url:
          "https://www.inputmag.com/tech/heres-every-product-amazon-just-announced",
      },
      {
        _id: "bb8abfe7-f1dbc84d",
        content_length: 6627,
        created_at: 1632863798000,
        feed_id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        feed_title: "Input",
        feed_color: [0, 65, 50],
        id:
          "https://www.inputmag.com/tech/amazons-alexa-everywhere-initiative-is-terrifying",
        title: "Amazon's 'Alexa Everywhere' initiative is terrifying",
        url:
          "https://www.inputmag.com/tech/amazons-alexa-everywhere-initiative-is-terrifying",
      },
    ],
    index: 0,
    lastUpdated: 1633093213159,
  },
  itemsSaved: { items: [], index: 0, lastUpdated: 1633093213159 },
  itemsMeta: { display: "unread", decoratedCount: 0 },
  feeds: {
    feeds: [
      {
        url: "https://www.inputmag.com/rss",
        title: "Input",
        description: "What comes next? Input is a new voice in tech news.",
        _id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        color: [0, 65, 50],
        number_unread: 50,
        id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        favicon: {
          url: "https://cdn2.bustle.com/input/2021/icon-17641d8f7a.png",
          size: null,
        },
        link: "https://www.inputmag.com/",
        inflatedDate: 1633093214423,
      },
    ],
    lastUpdated: 0,
  },
  feedsLocal: {
    feeds: [
      {
        _id: "f1dbc84d-e499-4f1a-ef5d-c62e5218e181",
        isNew: false,
        hasCachedIcon: true,
        cachedIconDimensions: { width: 180, height: 180 },
      },
    ],
  },
  ui: {
    viewButtonsVisible: false,
    itemButtonsVisible: false,
    modalVisible: false,
    modalProps: {
      modalText: [
        { text: "Add this feed?", style: ["title"] },
        { text: "Input", style: ["em"] },
        {
          text: "What comes next? Input is a new voice in tech news.",
          style: ["em", "smaller"],
        },
      ],
      modalHideCancel: false,
      modalShow: true,
    },
    showLoadingAnimation: false,
    imageViewerVisible: false,
    imageViewerUrl: "",
    hiddenModals: [],
    message: "",
    messageQueue: [],
    isDarkMode: false,
    fontSize: 3,
  },
  remoteActionQueue: { actions: [] },
  config: {
    backend: "basic",
    accessToken: "",
    isOnboarding: false,
    lastUpdated: 0,
    onboardingIndex: 1,
    onboardingLength: 13,
    filter: null,
    isOnline: true,
    itemSort: 0,
    showNumUnread: true,
    isItemsOnboardingDone: true,
    isFeedOnboardingDone: false,
  },
  user: {
    displayName: "",
    email: "",
    password: "",
    accessToken: "",
    signInEmail: "",
    uid: "",
    username: "",
  }
};
