require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'

target 'Reams' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # # third party deps
  pod 'ReactNativeShareExtension', :podspec => '../node_modules/react-native-share-extension/ReactNativeShareExtension.podspec'
  pod 'RNInAppBrowser', :path => '../node_modules/react-native-inappbrowser-reborn'

  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!

  # https://github.com/alinz/react-native-share-extension/issues/182
  target 'ReamsShare' do
    use_native_modules!
    inherit! :complete
  end
end

# Add this, taken from: https://github.com/facebook/react-native/issues/25792#issuecomment-517295859
# https://github.com/alinz/react-native-share-extension/issues/182
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
  flipper_post_install(installer)
end
