# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"

platform :ios do
  desc "Push a new build to TestFlight"
  lane :alpha do
    ENV["ENVFILE"] = ".env.alpha"
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "Reams.xcodeproj")
    build_app(
      scheme: "Reams",
      include_bitcode: false,
      xcargs: "UseModernBuildSystem=0")
    upload_to_testflight(
      skip_waiting_for_build_processing: true)
  end
  lane :beta do
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "Reams.xcodeproj")
    build_app(
      scheme: "Reams",
      include_bitcode: false,
      xcargs: "UseModernBuildSystem=0")
    upload_to_testflight(
      skip_waiting_for_build_processing: true)
  end
end
