# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"

platform :ios do
  desc "Push a new build to TestFlight"
  lane :alpha do
    ENV["FLAG_PLUS"] = "true"
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "Reams.xcodeproj")
    build_app(
      scheme: "Reams",
      include_bitcode: false,
      xcargs: "UseModernBuildSystem=0",
      export_options: {
        provisioningProfiles: {
          "com.adam-butler.rizzle" => "Reams App Store iOS",
          "com.adam-butler.rizzle.share" => "Reams ShareEx App Store ArtsyMBP"
        }
      }
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true)
  end
  lane :beta do
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "Reams.xcodeproj")
    commit_version_bump(
      message: "chore: version bump",
      xcodeproj: "Reams.xcodeproj"
    )
    add_git_tag
    push_to_git_remote
    build_app(
      scheme: "Reams",
      include_bitcode: false,
      xcargs: "UseModernBuildSystem=0",
      export_options: {
        provisioningProfiles: {
          "com.adam-butler.rizzle" => "Reams App Store iOS",
          "com.adam-butler.rizzle.share" => "Reams ShareEx App Store ArtsyMBP"
        }
      }
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true)
  end
end
