[{
  "title": "Singularity Hub",
  "url": "http://singularityhub.com/feed/",
  "description": "News and Insights on Technology, Science, and the Future from Singularity University"
}, {
  "title": "Futurity",
  "url": "http://www.futurity.org/feed/",
  "description": "Research news from top universities."
}, {
  "title": "Futurist Speaker",
  "url": "http://www.futuristspeaker.com/feed/",
  "description": "Thomas Frey futurist speaker works closely with his Board of Visionaries. He speaks on unusual topics and translates trends into business opportunities."
}, {
  "title": "The Long Now Blog",
  "url": "http://feeds.feedburner.com/longnow",
  "description": "The Official Weblog of The Long Now Foundation and Friends"
}, {
  "title": "Future Timeline | Latest Updates | Technology | Singularity | 2020 | 2050 | 2100 | 2150 | 2200 | 2..",
  "url": "http://feedity.com/futuretimeline-net/VVFXVFdV.rss",
  "description": "RSS Feed for Future Timeline | Latest Updates | Technology | Singularity | 2020 | 2050 | 2100 | 2150 | 2200 | 2.. (Generated by Feedity)"
}, {
  "title": "Futurist.com: Glen Hiemstra",
  "url": "http://feeds.feedburner.com/futuristcom",
  "description": "Glen Hiemstra is a futurist, keynote speaker, author, consultant, and Founder of Futurist.com."
}, {
  "title": "Gerd Leonhard Futurist Humanist Author Keynote Speaker",
  "url": "http://www.futuristgerd.com/feed/",
  "description": "Futurist, Humanist, Keynote Speaker, Author and Film-Maker: Gerd is CEO of the The Futures Agency and the global expert and presenter for Technology and Humanity, Digital Ethics, Artificial Intelligence and Digital Transforming"
}, {
  "title": "The Futurist",
  "url": "http://www.singularity2050.com/atom.xml",
  "description": "\"We know what we are, but we know not what we may become\" - William Shakespeare"
}, {
  "title": "Impact Lab",
  "url": "http://www.impactlab.net/feed/",
  "description": "A Laboratory of the Future Human Experience"
}, {
  "title": "BBC Future",
  "url": "http://www.bbc.com/future/feed.rss",
  "description": "The technology, science, environment and health site from the BBC. Exploring the ideas and innovations that are shaping our lives and the world around us."
}, {
  "title": "ExtremeTechExtreme – ExtremeTech",
  "url": "http://www.extremetech.com/category/Extreme/feed",
  "description": "ExtremeTech is the Web's top destination for news and analysis of emerging science and technology trends, and important software, hardware, and gadgets."
}, {
  "title": "NextBigFuture.com",
  "url": "http://feeds.feedburner.com/blogspot/advancednano",
  "description": "Coverage of Disruptive Science and Technology"
}, {
  "title": "TFOT",
  "url": "http://feedproxy.google.com/tfot",
  "description": "Science and technology e-magazine covering exclusive innovation from around the world. In-depth coverage of cutting edge science, technology and medicine related developments."
}, {
  "title": "Ethical Technology",
  "url": "http://feeds.feedburner.com/EthicalTechnology",
  "description": "Promoting the ethical use of technology to expand human capacities"
}, {
  "title": "Kurzweil",
  "url": "http://www.kurzweilai.net/feed/atom",
  "description": "Launched in 2001, KurzweilAI explores the forecasts and insights on accelerating change articulated in Ray Kurzweil’s landmark books."
}, {
  "title": "Futurist, Business Trends & Leadership Expert",
  "url": "http://www.jimcarroll.com/feed/",
  "description": "Turning Organizations into High Velocity Innovation heroes"
}, {
  "title": "the next wave",
  "url": "http://thenextwavefutures.wordpress.com/feed/",
  "description": "Andrew Curry's blog on futures, trends, emerging issues and scenarios"
}, {
  "title": "the sceptical futuryst",
  "url": "http://futuryst.blogspot.com/feeds/posts/default",
  "description": "a blog about how we might feel tomorrow"
}, {
  "title": "The Futures Agency | A global network of futurists and keynote speakers",
  "url": "http://www.thefuturesagency.com/rss",
  "description": "Futurize your business: search and book our amazing speakers and future-advisors"
}, {
  "title": "Singularity Weblog",
  "url": "http://feeds.feedburner.com/SingularityBlog",
  "description": "Singularity Weblog is a conversation about exponential tech, accelerating change, artificial intelligence and ethics: because technology is not enough!"
}, {
  "title": "Hinesight….for Foresight",
  "url": "http://www.andyhinesight.com/feed/",
  "description": "Applying foresight to help organizations make more creative, innovative, and forward looking decisions."
}, {
  "title": "FuturistechInfo Atom Feed",
  "url": "http://www.futuristech.info/4/feed",
  "description": "Futuristic stories from science, technology, economics, health, & other news sources; reporting on global trends impacting our future world"
}, {
  "title": "transhumanity.net",
  "url": "http://transhumanity.net/rss",
  "description": "the future of humanity now"
}, {
  "title": "Blog",
  "url": "http://www.diamandis.com/blog/rss.xml",
  "description": ""
}, {
  "title": "Reimagining the Future",
  "url": "http://frankdiana.wordpress.com/feed/",
  "description": "A Journey Through the Looking Glass"
}, {
  "title": "The more accurate guide to the future",
  "url": "http://timeguide.wordpress.com/feed/",
  "description": "thoughts from Futurizon's Dr Pearson"
}, {
  "title": "What's Next: Top Trends",
  "url": "http://toptrends.nowandnext.com/?feed=rss2",
  "description": "Diary of an accidental futurist - observations on current & future trends"
}, {
  "title": "Institute for the Future (IFTF)",
  "url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCfO9dW0L2vLc8s9qgZunUFA",
  "description": ""
}, {
  "title": "Lifeboat News: The Blog",
  "url": "http://lifeboat.com/blog/?feed=rss2",
  "description": "The Lifeboat Foundation blog has tens of thousands of scientific blog posts!"
}, {
  "title": "The Oakland Futurist",
  "url": "http://oaklandfuturist.com/feed/",
  "description": "Futurism, Cognitive Science, and Other Ideas from the Bay Area"
}, {
  "title": "Brad Ideas",
  "url": "http://ideas.4brad.com/index.rdf",
  "description": "Brad Templeton is Chairman Emeritus of the EFF, Singularity U founding computing faculty, software architect and internet entrepreneur, robotic car strategist, futurist lecturer, photographer and Burning Man artist. This is an \"ideas\" blog rather than a \"cool thing I saw today\" blog. Many of the items are not topical. If you like what you read, I recommend you also browse back in the archives, starting with the best of blog section. It also has various\"topic\" and \"tag\" sections (see menu on right) and some are sub blogs like Robocars, photography and Going Green. Try my home page for more info and contact data."
}, {
  "title": "By Matthew Griffin Futurist and Keynote Speaker",
  "url": "http://www.globalfuturist.org/feed/",
  "description": "Matthew Griffin, award winning futurist and international keynote speaker, also known as the \"Fanatical Futurist\" demystifies and brings the future to life."
}, {
  "title": "Slate Magazine",
  "url": "http://www.slate.com/blogs/future_tense.fulltext.all.10.rss",
  "description": "Online magazine of news, politics, technology, and culture. Combines humor and insight in thoughtful analyses of current events and political news."
}, {
  "title": "Foresight Institute",
  "url": "http://www.foresight.org/nanodot/wp-rss.php",
  "description": "Foresight Institute is a non-profit organization focused on advancing technologies of fundamental importance for the future of life."
}, {
  "title": "Decline Of Scarcity",
  "url": "http://feeds.feedburner.com/TheDeclineOfScarcity",
  "description": "Personal Finance Enhanced!"
}, {
  "title": "21st Century Tech Blog",
  "url": "http://www.21stcentech.com/feed/",
  "description": "Science, Technology and the Future"
}, {
  "title": "Jack Uldrich",
  "url": "http://jackuldrich.com/feed/",
  "description": ""
}, {
  "title": "NFA CFTC Rule Submission Letters",
  "url": "http://www.nfa.futures.org/rss/ruleSubmissionsRSS.xml",
  "description": "List of Rule Submissions to the CFTC"
}, {
  "title": "gordonmcdowell (uploads) on YouTube",
  "url": "http://gdata.youtube.com/feeds/base/users/gordonmcdowell/uploads?alt=rss&v=2&orderby=published&client=ytapi-youtube-profile",
  "description": "Videographer in Calgary, Alberta, Canada. Thorium & MSR advocate. Working to educate public on Molten Salt Reactors, Liquid Fluoride Thorium Reactors, and the reasons that today's reactors are not what nuclear power ought to be."
}, {
  "title": "The Medical Futurist",
  "url": "http://scienceroll.com/feed/",
  "description": "We strongly believe that only digital health can bring healthcare into the 21st century and make patients the point-of-care."
}, {
  "title": "SpaceCollective posts",
  "url": "http://spacecollective.org/feed-rss.php?t=a&f=po",
  "description": ""
}, {
  "title": "NFA Regulatory Actions",
  "url": "http://www.nfa.futures.org/rss/regActionsRSS.xml",
  "description": "NFA is the industry wide, self-regulatory organization for the U.S. derivatives industry, providing innovative and effective regulatory programs."
}, {
  "title": "Humanity+",
  "url": "http://humanityplus.org/feed/",
  "description": "Humanity+ is the world's largest transhumanist organization that advocates ethical use of technology and evidence-based science for radical life extension."
}, {
  "title": "Future of Life Institute",
  "url": "http://futureoflife.org/feed/",
  "description": "Technology is giving life the opportunity to flourish like never before... or to self-destruct."
}, {
  "title": "Future Thinkers",
  "url": "http://futurethinkers.org/feed/",
  "description": "The Evolution of Society, Technology and Consciousness"
}, {
  "title": "InsideFutures.com Commentary",
  "url": "http://www.insidefutures.com/rss/rss20.php",
  "description": "Futures market commentary from leading industry experts."
}, {
  "title": "Open Source Ecology",
  "url": "http://blog.opensourceecology.org/feed/",
  "description": "We’re developing open source industrial machines that can be made for a fraction of commercial costs, and sharing our designs online for free. The goal of Open Source Ecology is to create an open source economy – an efficient economy which increases innovation by open collaboration."
}]